const mutationTypes = {
  SET_CURRENT_F0RECAST: 'SET_CURRENT_F0RECAST',
  SET_COORD: 'SET_COORD',
  SET_WEEK_FORECAST: 'SET_WEEK_FORECAST',
  SET_SEARCH_STATUS: 'SET_SEARCH_STATUS'
}

export default mutationTypes
